service: dont-forget-me
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: src/app.handler
    events:
      - http:
          path: /
          method: GET
          cors: false
      - http:
          path: /users
          method: GET
          cors: false
      - http:
          path: /login
          method: POST
          cors: false
      - http:
          path: /user/create
          method: POST
          cors: false
      - http:
          path: /user/{email}
          method: GET
          cors: false
      - http:
          path: /user/by/personal_info
          method: POST
          cors: false
      - http:
          path: /user/update/{email}
          method: PUT
          cors: false
      - http:
          path: /user/delete/{email}
          method: DELETE
          cors: false
